### PR TITLE
[RTM] Check if framework is available

### LINKED ISSUE #71: Contao framework not initialized upon invalid route
If you enter a URL that is not matched by a route (e.g. `http://contao.local/`), the Contao framework does not get initialized:

```
Fatal error: Class 'Contao\Frontend' not found in ~/contao/standard-edition/vendor/contao/core-bundle/src/EventListener/OutputFromCacheListener.php on line 31
```

The problem is that the Symfony exception listener is a sub request and we have recently added the following lines:

```php
// InitializeSystemListener::onKernelRequest()
if (!$event->isMasterRequest()) {
    return;
}
```

@aschempp How do we handle this case?

### PR DESCRIPTION
**Pull request by aschempp**
fixes #71

### CODE REVIEW

File: src/EventListener/AddToSearchIndexListener.php [hunk 1]
```diff
@@ -27,6 +27,12 @@ class AddToSearchIndexListener
      */
     public function onKernelTerminate(PostResponseEvent $event)
     {
+        if (!defined('TL_ROOT')) {
```
Comment (Toflar) [inline src/EventListener/AddToSearchIndexListener.php]: Add a `FIXME:` here please, because we must not use constants anymore.

File: src/EventListener/AddToSearchIndexListener.php [hunk 2]
```diff
@@ -27,6 +27,12 @@ class AddToSearchIndexListener
...
+            return;
+        }
+
+        // TODO: we should also find a way to check for the master reqeust
```
Comment (Toflar) [inline src/EventListener/AddToSearchIndexListener.php]: Switch this to a `FIXME` :)

Comment (aschempp) [inline src/EventListener/AddToSearchIndexListener.php]: done

**Comment by aschempp** [comment]
I have updated this PR to include the part about not booting the framework if there is no request scope. I also figured out we incorrectly checked for the request scope instead of the container scope in all places, but that's fixed here too.

File: src/DependencyInjection/Compiler/AddPackagesPass.php [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+        }
+
+        foreach ($composerData as $package) {
+            $name = str_replace("'", "\\'", $package['name']);
+            $version = substr($package['version_normalized'], 0, strrpos($package['version_normalized'], '.'));
+
+            if (preg_match('/^[0-9]+\.[0-9]+\.[0-9]+$/', $version)) {
+                $packages[$name] = $version;
+            } elseif (isset($package['extra']['branch-alias'][$package['version_normalized']])) {
+                // FIXME: this is wrong, 4.0.x-dev would result in 4.0.999999
```
Comment (leofeyer) [inline src/DependencyInjection/Compiler/AddPackagesPass.php]: Why do you think this is wrong?

File: src/EventListener/InitializeSystemListener.php [hunk 4]
```diff
@@ -301,7 +299,7 @@ private function validateInstallation(Config $config, $routeName)
 
         // Show the "insecure document root" message
         if ('/web' === substr(Environment::get('path'), -4)) {
-            die_nicely('be_insecure', 'Your installation is not secure. Please set the document root to the <code>/web</code> subfolder.');
+            //die_nicely('be_insecure', 'Your installation is not secure. Please set the document root to the <code>/web</code> subfolder.');
```
Comment (leofeyer) [inline src/EventListener/InitializeSystemListener.php]: We should not commit this, should we?

**Comment by leofeyer** [comment]
> I also figured out we incorrectly checked for the request scope instead of the container scope

What did we do wrong?

File: src/DependencyInjection/Compiler/AddPackagesPass.php (hunk 3 above)
Comment (aschempp) [inline src/DependencyInjection/Compiler/AddPackagesPass.php]: Because 4.0.x-dev should be smaller than 4.0.0.

File: src/EventListener/InitializeSystemListener.php (hunk 4 above)
Comment (aschempp) [inline src/EventListener/InitializeSystemListener.php]: doh, that was from local testing. Fixed it

**Comment by aschempp** [comment]
> > I also figured out we incorrectly checked for the request scope instead of the container scope

> What did we do wrong?

We must not check `$request->attributes->get('_scope')` instead we must check `$container->isScopeActive('…')`.

I also moved the packages information to the container. Apart from the advantage of caching and not being in the System class, it was necessary to have the Contao version available in the new code (in this case for the profiler) even if the legacy framework is not booted.

For all the changed I changed the title back to RFC for @contao/developers to review.

File: src/DependencyInjection/Compiler/AddPackagesPass.php (hunk 3 above)
Comment (leofeyer) [inline src/DependencyInjection/Compiler/AddPackagesPass.php]: Nope: https://github.com/composer/composer/blob/master/src/Composer/Package/Version/VersionParser.php#L208

Comment (aschempp) [inline src/DependencyInjection/Compiler/AddPackagesPass.php]: I see, so they assume that the `4.0.x-dev`-branch is a maintenance version of `4.0`. That would only be correct for hotfix branched, but not for `develop`. But they also keep the dev-flag, we should probably keep that too?

File: tests/bootstrap.php [hunk 5]
```diff
@@ -47,5 +47,6 @@ class_alias("Contao\\$class", $class);
 
 /** @var Composer\Autoload\ClassLoader $loader */
 $loader->addPsr4('Contao\\CoreBundle\\Test\\', __DIR__);
+$loader->addPsr4('Contao\\Fixtures\\', __DIR__.'/Fixtures');
```
Comment (leofeyer) [inline tests/bootstrap.php]: This cannot be right. Do you mean `'Contao\\CoreBundle\\Test\\Fixtures'`?

File: src/Command/InstallCommand.php [hunk 6]
```diff
@@ -64,15 +64,14 @@ protected function configure()
      */
     protected function executeLocked(InputInterface $input, OutputInterface $output)
     {
-        $fs      = new Filesystem();
-        $rootDir = dirname($this->getContainer()->getParameter('kernel.root_dir'));
+        $fs = new Filesystem();
 
         foreach ($this->emptyDirs as $path) {
-            $this->addEmptyDir("$rootDir/$path", $fs, $output);
+            $this->addEmptyDir(getcwd() . "/$path", $fs, $output);
```
Comment (leofeyer) [inline src/Command/InstallCommand.php]: Why did you change this to `getcwd()`? Now the script can only be run from the installation root directory, which is wrong. It is ok to use `getcwd()` in a Composer script handler, because Composer **always** runs in the installation root directory. But `app/console` does not, so please revert this.

File: src/EventListener/AddToSearchIndexListener.php [hunk 7]
```diff
@@ -27,6 +27,11 @@ class AddToSearchIndexListener
      */
     public function onKernelTerminate(PostResponseEvent $event)
     {
+        // FIXME: should be replaced with "Response implements Indexable" (see https://github.com/contao/symfony-todo/issues/3)
+        if (!defined('TL_ROOT')) {
```
Comment (leofeyer) [inline src/EventListener/AddToSearchIndexListener.php]: Why did you add an additional check? `Frontend::indexPageIfApplicable()` will decide itself when indexing is applicable (hence the method name).

File: src/EventListener/ContainerScopeListener.php [hunk 8]
```diff
@@ -40,9 +41,9 @@ public function __construct(ContainerInterface $container)
     /**
      * Enters the container scope when a route has been found.
      *
-     * @param FilterControllerEvent $event
+     * @param GetResponseEvent $event
      */
-    public function onKernelController(FilterControllerEvent $event)
+    public function onKernelRequest(GetResponseEvent $event)
```
Comment (leofeyer) [inline src/EventListener/ContainerScopeListener.php]: Why are we now listening on the `kernel.request` event?

File: src/Resources/config/services.yml [hunk 9]
```diff
@@ -9,7 +9,7 @@ services:
         arguments:
             - "@service_container"
         tags:
-            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 254 }
+            - { name: kernel.event_listener, event: kernel.controller, method: onKernelRequest, priority: 31 }
```
Comment (leofeyer) [inline src/Resources/config/services.yml]: I assume you have set the priority to `31` on purpose. Can you elaborate please?

**Comment by leofeyer** [comment]
Aside from my comments above and the failing tests, this PR looks good to me. Can you finish it and then change the title to `[RTM]` please?

File: tests/bootstrap.php (hunk 5 above)
Comment (aschempp) [inline tests/bootstrap.php]: This is part of #159, @dtomasi needs to answer that.

File: src/Command/InstallCommand.php (hunk 6 above)
Comment (aschempp) [inline src/Command/InstallCommand.php]: That's merged from your commit (f02f9ac8faf14b4f4c1433fbe0fe4b813e5d6b54)

File: src/EventListener/AddToSearchIndexListener.php (hunk 7 above)
Comment (aschempp) [inline src/EventListener/AddToSearchIndexListener.php]: Class `Frontend` would not be available without the framework.

File: src/EventListener/ContainerScopeListener.php (hunk 8 above)
Comment (aschempp) [inline src/EventListener/ContainerScopeListener.php]: Because otherwise the container scope would not be set in the `InitializeSystemListener`

File: src/Resources/config/services.yml (hunk 9 above)
Comment (aschempp) [inline src/Resources/config/services.yml]: Priority 32 is the routing listener, priority 30 is the `InitializeSystemListener`. The container scope must be set between them.

File: src/Command/InstallCommand.php (hunk 6 above)
Comment (leofeyer) [inline src/Command/InstallCommand.php]: Oh, good we noticed this :)

File: src/Resources/config/services.yml (hunk 9 above)
Comment (leofeyer) [inline src/Resources/config/services.yml]: Should we probably set the priority of the `InitializeSystemListener` to 28 and the one of the `ContainerScopeListener` to 30 then? In case anyone needs to add a custom listener in between any of them.

Comment (aschempp) [inline src/Resources/config/services.yml]: I have changed all priorities accordingly in 36ba667a261dee51f830e0237af523aab1419220

**Comment by aschempp** [comment]
Fixed and rebased everything.

File: tests/bootstrap.php (hunk 5 above)
Comment (discordier) [inline tests/bootstrap.php]: The namespace is used in https://github.com/contao/core-bundle/pull/76/files#diff-f95982ace6744c19f506f6fb5e0b26b6R11, therefore he had to add this here.

Problem here is, we defined our fixtures with the old autoloader compat to reside in `tests/Fixtures/library` and having the complete namespace of `Contao\\Fixtures`. I guess @dtomasi was confused by this unorthodox directory layout.

File: src/EventListener/InitializeSystemListener.php [hunk 10]
```diff
@@ -86,27 +86,28 @@ public function onKernelRequest(GetResponseEvent $event)
...
      */
-    private function getScopeFromRequest(Request $request)
+    private function getScopeFromContainer()
     {
-        if ($request->attributes->has('_scope') && 'backend' === $request->attributes->get('_scope')) {
+        if ($this->container->isScopeActive('backend')) {
             return 'BE';
+        } elseif ($this->container->isScopeActive('frontend')) {
+            return 'FE';
+        } else {
```
Comment (discordier) [inline src/EventListener/InitializeSystemListener.php]: This `else` is not needed and will increase cyclomatic complexity with some tools.
Please rewrite as:
```php
if ($this->container->isScopeActive('backend')) {
    return 'BE';
} elseif ($this->container->isScopeActive('frontend')) {
    return 'FE';
}
return null;
```

File: tests/bootstrap.php (hunk 5 above)
Comment (dtomasi) [inline tests/bootstrap.php]: @discordier is absolutely right. That's a bit unorthodox in SF2's world. So I set this namespace as usual.

File: src/EventListener/InitializeSystemListener.php (hunk 10 above)
Comment (aschempp) [inline src/EventListener/InitializeSystemListener.php]: Changed in b82467f88249a211b5efc778c42b444dd51712fa

**Comment by aschempp** [comment]
I have again optimized the code to get only A's in Scrutinizer :-)

**Comment by leofeyer** [comment]
Merged in b207989883927382a6bbda552b93f084425384e6. There are some open questions though:

1. https://github.com/contao/core-bundle/blob/develop/src/Resources/config/services.yml#L73

My IDE says "missing parameter" here.

2. https://github.com/contao/core-bundle/blob/develop/tests/TestCase.php#L119-L120

We are using `new Scope('…')` here, but we are using `new Scope('…', 'request')` in the `ContaoCoreBundle` class:

https://github.com/contao/core-bundle/blob/develop/src/ContaoCoreBundle.php#L42-L43

**Comment by aschempp** [comment]
> https://github.com/contao/core-bundle/blob/develop/src/Resources/config/services.yml#L73
My IDE says "missing parameter" here.

That's because you did not run dev environment. The inspector uses data from the cache folder.

> We are using new Scope('…') here, but we are using new Scope('…', 'request') in the ContaoCoreBundle class: https://github.com/contao/core-bundle/blob/develop/src/ContaoCoreBundle.php#L42-L43
Which one is correct?

`request` would be the parent one. In the tests, there is no parent scope of type request (because the `HttpKernel` did not handle it. So the current is correct.
